import {createWorld} from './scene.js';
import {CONFIG,TARGETS,PLANET_NAMES,RAY_COLORS,duration,formatTime,normalizeState} from './state.js';
import {SYMBOLISM} from './symbolism.js';
const $=s=>document.querySelector(s),panel=$('#panel'),content=$('#panel-content'),drawer=$('#history-drawer'),person=$('#person'),actions=$('#context-actions'),bubble=$('#stage-popover');
const systemLabels=document.createElement('div');systemLabels.id='system-labels';systemLabels.hidden=true;$('#app').append(systemLabels);const systemButtons=new Map(),systemLines=new Map();for(const name of PLANET_NAMES.filter(n=>n!=='Луна')){const b=document.createElement('button');b.textContent=name;b.onclick=()=>world?.visit(name);const line=document.createElement('span');line.className='system-leader';systemLabels.append(line,b);systemButtons.set(name,b);systemLines.set(name,line);}
let state,world,current,focusMode='initial',selectedPlanet='Земля',context=null,expanded=false,storageOK=true,activeRayId=null;
try{const raw=JSON.parse(localStorage.getItem(CONFIG.storageKey)||'null'),legacy=JSON.parse(localStorage.getItem(CONFIG.legacyKey)||'[]');state=normalizeState(raw,legacy);if(!raw){try{state.goals=normalizeState({goals:JSON.parse(localStorage.getItem('dlit-volyu:goals:v1')||'[]')}).goals;}catch{}}}catch{state=normalizeState(null);storageOK=false;}
current=state.acts.find(a=>a.endedAt===null&&state.rays.some(r=>r.id===a.rayId&&!r.deletedAt));
const notify=text=>{$('#notice').textContent=text;$('#notice').hidden=false;setTimeout(()=>$('#notice').hidden=true,6500)};
const liveRays=()=>state.rays.filter(r=>!r.deletedAt);
const liveActs=()=>state.acts.filter(a=>state.rays.some(r=>r.id===a.rayId&&!r.deletedAt));
const defaultRayName=()=>liveRays().length?'Луч '+(liveRays().length+1):'Воля';
let undoRayId=null;
const destination=r=>r?.target==='Своя цель'?(r.goal||'Своя цель'):(r?.target||'Бесконечность');
const rayFor=a=>state.rays.find(r=>r.id===a.rayId);
const stageFor=a=>state.acts.filter(x=>x.rayId===a.rayId).slice().reverse().findIndex(x=>x.id===a.id)+1;
const dateText=t=>new Intl.DateTimeFormat('ru',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(t);
function save(){try{localStorage.setItem(CONFIG.storageKey,JSON.stringify(state));storageOK=true;}catch{storageOK=false;notify('Не удалось сохранить на устройстве. Пока запись доступна только в открытой вкладке.');}}
function render(){world?.setState({...state,rays:liveRays()});sync();}
function sync(){$('#intro').hidden=focusMode!=='initial';$('#timer').hidden=!current;if(current)$('#timer output').value=formatTime(duration(current));}
function hideStage(){bubble.hidden=true;world?.dismissAct();}
function updateActions(){actions.hidden=context!=='human'||panel.open||!drawer.hidden||!bubble.hidden;$('#context-plus').setAttribute('aria-expanded',String(expanded));$('#human-actions').hidden=!expanded;}
function close(){panel.close();panel.classList.remove('entry');updateActions();}
function closeHistory(){drawer.hidden=true;$('#history').setAttribute('aria-expanded','false');updateActions();}
function open(html,label,entry=false){hideStage();closeHistory();content.innerHTML=html;panel.setAttribute('aria-label',label);panel.classList.toggle('entry',entry);if(!panel.open)panel.showModal();updateActions();}
function metaRow(dl,label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;dl.append(dt,dd);}
function actDetails(a){const ray=rayFor(a),dl=document.createElement('dl');dl.className='act-details';metaRow(dl,'Луч',ray?.name||'Воля');metaRow(dl,'Устремление',destination(ray));metaRow(dl,'Этап',String(stageFor(a)));metaRow(dl,'Создан',dateText(a.startedAt));metaRow(dl,'Длительность',formatTime(duration(a)));return dl;}
function showHistory(selectedId){hideStage();close();drawer.hidden=false;$('#history').setAttribute('aria-expanded','true');const list=$('#acts-list');list.replaceChildren();const acts=liveActs();$('#history-empty').hidden=!!acts.length;
 for(const a of acts){const row=document.createElement('li'),card=document.createElement('details'),summary=document.createElement('summary'),text=document.createElement('span'),chevron=document.createElement('span');row.className='act-card'+(a.id===selectedId?' selected':'');row.dataset.id=a.id;card.open=a.id===selectedId;text.className='act-content';text.textContent=a.text;chevron.className='card-chevron';chevron.textContent='⌄';chevron.setAttribute('aria-hidden','true');const heading=document.createElement('span'),copy=document.createElement('span');copy.className='act-summary-copy';heading.className='act-ray-title';heading.textContent=rayFor(a)?.name||'Воля';heading.style.color=rayFor(a)?.color||RAY_COLORS[6][0];copy.append(heading,text);summary.append(copy,chevron);card.append(summary,actDetails(a));const edit=document.createElement('button');edit.className='text-action';edit.textContent='Настроить луч';edit.onclick=()=>editRay(a.rayId,()=>showHistory(a.id));const travel=document.createElement('button');travel.className='text-action';travel.textContent='Перейти к лучу';travel.onclick=()=>{closeHistory();world?.selectRay(a.rayId);};if(!rayFor(a)?.deletedAt){const actions=document.createElement('div');actions.className='act-card-actions';actions.append(edit,travel);card.append(actions);}row.append(card);list.append(row);}
 if(selectedId)[...list.children].find(e=>e.dataset.id===selectedId)?.scrollIntoView({block:'nearest'});updateActions();}
function showStage(a){close();closeHistory();bubble.replaceChildren();const dismiss=document.createElement('button');dismiss.className='popover-close';dismiss.setAttribute('aria-label','Закрыть этап');dismiss.textContent='×';dismiss.onclick=()=>{hideStage();updateActions();};const title=document.createElement('div');title.className='stage-heading';title.textContent=(rayFor(a)?.name||'Воля')+' · Этап '+stageFor(a);const text=document.createElement('p');text.className='stage-content';text.textContent=a.text;const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Подробнее';details.append(summary,actDetails(a));bubble.append(dismiss,title,text,details);bubble.hidden=false;updateActions();}
function selector(label,id,options){const wrap=document.createElement('label');wrap.className='field-label';wrap.textContent=label;const select=document.createElement('select');select.id=id;select.setAttribute('aria-label',label);for(const [value,text]of options){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}wrap.append(select);return{wrap,select};}
function nameField(value){const wrap=document.createElement('label');wrap.className='field-label';wrap.textContent='Название луча';const input=document.createElement('input');input.id='ray-name';input.setAttribute('aria-label','Название луча');input.maxLength=80;input.value=value;input.autocomplete='off';wrap.append(input);return{wrap,input};}
function rayFields(container,initial={}){const name=nameField(initial.name||defaultRayName()),target=selector('Устремление','target',TARGETS.map(t=>[t,t==='Бесконечность'?'В бесконечность':t]));const goalWrap=document.createElement('label');goalWrap.className='field-label';goalWrap.textContent='Своя цель';const goal=document.createElement('textarea');goal.id='ray-goal';goal.maxLength=300;goal.setAttribute('aria-label','Своя цель');goalWrap.append(goal);const palette=document.createElement('fieldset');palette.className='ray-palette';const legend=document.createElement('legend');legend.textContent='Цвет луча';palette.append(legend);let color=initial.color||RAY_COLORS[6][0];const choices=[];for(const [hex,label]of RAY_COLORS){const b=document.createElement('button');b.type='button';b.className='color-choice';b.style.setProperty('--swatch',hex);b.setAttribute('aria-label',label);b.onclick=()=>{color=hex;refresh();};palette.append(b);choices.push([b,hex]);}const refresh=()=>{for(const [b,hex]of choices)b.setAttribute('aria-pressed',String(color===hex));goalWrap.hidden=target.select.value!=='Своя цель';goal.required=!goalWrap.hidden;};const load=r=>{name.input.value=r?.name||defaultRayName();target.select.value=r?.target||'Бесконечность';goal.value=r?.goal||'';color=r?.color||RAY_COLORS[6][0];refresh();};target.select.onchange=refresh;container.append(name.wrap,target.wrap,goalWrap,palette);load(initial);return{name:name.input,target:target.select,load,refresh,read:()=>({name:name.input.value.trim()||defaultRayName(),target:target.select.value,goal:target.select.value==='Своя цель'?goal.value.trim():'',color})};}
function form(kind){expanded=false;const forceNew=kind==='ray';open('<form id="intention-form"><textarea id="intention" maxlength="500" aria-label="Содержание акта" placeholder="Первый акт нового луча" required></textarea><div id="form-options"></div><button class="outline" type="submit">УТВЕРДИТЬ</button></form>',forceNew?'Новый луч с актом':'Новый акт',true);const input=$('#intention'),options=$('#form-options');let raySelect;
 if(!forceNew&&liveRays().length){const picker=selector('Луч','ray-select',[['new','Новый луч'],...liveRays().map(r=>[r.id,r.name])]);raySelect=picker.select;raySelect.value=liveRays().some(r=>r.id===activeRayId)?activeRayId:liveRays().at(-1).id;options.append(picker.wrap);input.removeAttribute('placeholder');}
 const selected=liveRays().find(r=>r.id===raySelect?.value),fields=rayFields(options,selected);
 if(raySelect){raySelect.onchange=()=>fields.load(liveRays().find(r=>r.id===raySelect.value));fields.target.onchange=()=>{const r=liveRays().find(r=>r.id===raySelect.value);if(r&&r.target!==fields.target.value){raySelect.value='new';fields.name.value=defaultRayName();}fields.refresh();};}
 const submit=$('#intention-form button[type="submit"]');submit.disabled=true;input.oninput=()=>submit.disabled=!input.value.trim();$('#intention-form').onsubmit=e=>{e.preventDefault();const settings=fields.read();if(!input.value.trim()||settings.target==='Своя цель'&&!settings.goal)return;approve(input.value,settings.target,raySelect?.value||'new',settings.name,settings);};input.focus();}
function createRay(name,target,settings={}){if(!TARGETS.includes(target))throw new Error('Выбери направление луча.');const ray={id:crypto.randomUUID(),name:name.trim().slice(0,80)||defaultRayName(),target,color:settings.color||RAY_COLORS[6][0],goal:settings.goal||'',createdAt:Date.now()};state.rays.push(ray);return ray;}
function approve(text,target='Бесконечность',rayId='new',name='',settings={}){if(typeof text!=='string'||!text.trim()||text.trim().length>500)throw new Error('Введи от 1 до 500 символов.');if(!TARGETS.includes(target))throw new Error('Неизвестное направление.');if(target==='Своя цель'&&!settings.goal?.trim())throw new Error('Укажи свою цель.');let ray=liveRays().find(r=>r.id===rayId&&r.target===target);if(!ray)ray=createRay(name||defaultRayName(),target,settings);else{if(name.trim())ray.name=name.trim().slice(0,80);if(settings.color)ray.color=settings.color;if(settings.goal!==undefined)ray.goal=settings.goal;}const now=Date.now();if(current)current.endedAt=now;current={id:crypto.randomUUID(),text:text.trim(),rayId:ray.id,startedAt:now,endedAt:null};state.acts.unshift(current);save();render();close();context=null;updateActions();return{id:current.id,rayId:ray.id,target:ray.target};}
function editRay(id,after){const ray=state.rays.find(r=>r.id===id);if(!ray)return;open('<form id="rename-ray"><h2>НАСТРОЙКИ ЛУЧА</h2><div id="rename-field"></div><button class="outline" type="submit">СОХРАНИТЬ</button><button id="delete-ray" class="delete-ray" type="button">Удалить луч</button></form>','Настройки луча',true);const fields=rayFields($('#rename-field'),ray);fields.name.required=true;$('#rename-ray').onsubmit=e=>{e.preventDefault();const settings=fields.read();if(settings.target==='Своя цель'&&!settings.goal)return;Object.assign(ray,settings);save();render();close();after?.();};$('#delete-ray').onclick=()=>removeRay(id);fields.name.focus();}
function removeRay(id){const ray=liveRays().find(r=>r.id===id);if(!ray)return;ray.deletedAt=Date.now();if(current?.rayId===id){current.endedAt=ray.deletedAt;current=null;}undoRayId=id;if(activeRayId===id)world?.focus(false);save();render();showRays();}
function showRays(){open('<h2>ЛУЧИ</h2><div id="rays-list"></div><button id="new-ray" class="outline">+ ЛУЧ</button><div id="ray-undo"></div>','Лучи');const list=$('#rays-list');if(!liveRays().length){const p=document.createElement('p');p.className='rays-empty';p.textContent='Дай имя своему первому направлению.';list.append(p);}for(const ray of liveRays()){const card=document.createElement('article');card.className='ray-card';card.style.setProperty('--ray-color',ray.color||RAY_COLORS[6][0]);const title=document.createElement('h3'),target=document.createElement('p'),count=document.createElement('small'),buttons=document.createElement('div');title.textContent=ray.name;target.textContent=destination(ray);count.textContent='Этапов: '+state.acts.filter(a=>a.rayId===ray.id).length;buttons.className='ray-card-actions';for(const [label,action]of [['Перейти',()=>{close();world?.selectRay(ray.id);}],['Настроить',()=>editRay(ray.id,showRays)]]){const button=document.createElement('button');button.textContent=label;button.onclick=action;buttons.append(button);}card.append(title,target,count,buttons);list.append(card);}$('#new-ray').onclick=()=>form('ray');if(undoRayId){const undo=document.createElement('button');undo.className='text-action';undo.textContent='Луч удалён. Вернуть';undo.onclick=()=>{const r=state.rays.find(r=>r.id===undoRayId);if(r)delete r.deletedAt;undoRayId=null;save();render();showRays();};$('#ray-undo').append(undo);}}
function planetCaption(name){const body=world?.getBody(name);const [symbol,meaning]=SYMBOLISM[name]||['☾',body?.parent?'Спутник · '+body.parent:''];$('#planet-title').textContent=symbol+' '+name;$('#planet-meaning').textContent=meaning;$('#planet-caption').hidden=false;$('#planet-goals').replaceChildren();$('#planet-moons').replaceChildren();for(const moon of world?.getMoons(name)||[]){const b=document.createElement('button');b.textContent=moon;b.onclick=()=>world.visit(moon);$('#planet-moons').append(b);}for(const g of state.goals.filter(g=>g.planet===name)){const p=document.createElement('p');p.textContent=g.text;$('#planet-goals').append(p);}}
try{world=createWorld($('#world'),{
 onFrame:p=>{systemLabels.hidden=!p.systemBodies||panel.open||!drawer.hidden;if(p.systemBodies){const occupied=[];for(const b of p.systemBodies){const el=systemButtons.get(b.name),line=systemLines.get(b.name);el.hidden=!b.visible;line.hidden=!b.visible;if(!b.visible)continue;const x=Math.max(48,Math.min(p.width-48,b.x));let y=b.y+18;while(occupied.some(o=>Math.abs(o.x-x)<90&&Math.abs(o.y-y)<25))y+=26;occupied.push({x,y});el.style.left=x+'px';const labelY=Math.min(p.height-110,Math.max(110,y));el.style.top=labelY+'px';const dx=x-b.x,dy=labelY-b.y;line.style.left=b.x+'px';line.style.top=b.y+'px';line.style.width=Math.hypot(dx,dy)+'px';line.style.transform='rotate('+Math.atan2(dy,dx)+'rad)';}}$('#person-card').hidden=!(p.mode==='human'&&p.humanZoom>=2&&p.visible&&!panel.open&&drawer.hidden&&bubble.hidden);person.style.left=p.x+'px';person.style.top=p.y+'px';person.hidden=!p.visible;actions.style.left=Math.min(p.width-155,Math.max(20,p.x+55))+'px';actions.style.top=Math.max(82,Math.min(p.height-140,p.y-20))+'px';actions.style.visibility=p.visible?'visible':'hidden';if(!bubble.hidden&&p.stage){const w=Math.min(280,p.width-32),height=bubble.offsetHeight||160;bubble.style.width=w+'px';let x=p.stage.x+20,y=p.stage.y-height/2;if(x+w>p.width-16){if(p.stage.x>w+36)x=p.stage.x-w-20;else{x=p.stage.x-w/2;y=p.stage.y-height-22>=88?p.stage.y-height-22:p.stage.y+22;}}bubble.style.left=Math.min(p.width-w-16,Math.max(16,x))+'px';bubble.style.top=Math.max(88,Math.min(p.height-height-24,y))+'px';bubble.style.visibility=p.stage.visible?'visible':'hidden';}},
 onAct:showStage,onRay:r=>{activeRayId=r.id;$('#rays').style.borderColor=r.color||RAY_COLORS[6][0];},
 onFocus:(mode,name)=>{hideStage();focusMode=mode;selectedPlanet=name;context=null;expanded=false;$('#planet-caption').hidden=mode!=='planet';if(mode==='planet')planetCaption(name);if(mode==='system'){$('#planet-caption').hidden=false;$('#planet-title').textContent='Солнечная система';$('#planet-meaning').textContent='Общий вид · расстояния сжаты для обзора';$('#planet-moons').replaceChildren();$('#planet-goals').replaceChildren();}if(mode!=='ray'){activeRayId=null;$('#rays').style.borderColor='';}updateActions();sync();},onNavigate:()=>{context=null;expanded=false;updateActions();},onError:notify});world.setState({...state,rays:liveRays()});world.setSkin('cap');}catch(e){notify('3D-пространство недоступно. Нужен браузер с WebGL.');console.error(e);}
person.onclick=()=>{closeHistory();world?.focus();context='human';updateActions();};$('#home').onclick=()=>{hideStage();close();closeHistory();world?.focus(false);context=null;updateActions();};$('#context-plus').onclick=()=>{if(context==='human'){expanded=!expanded;updateActions();}};$('#add-act').onclick=()=>form('act');$('#add-ray').onclick=()=>form('ray');

$('#planets').onclick=()=>{open('<button id="system-overview" class="system-overview"><strong>Солнечная система</strong><span>Посмотреть всю систему</span><i aria-hidden="true">↗</i></button><h2>ПЛАНЕТЫ</h2><div class="planet-list"></div>','Планеты');$('#system-overview').onclick=()=>{close();closeHistory();world?.systemView();};for(const name of PLANET_NAMES){const b=document.createElement('button');b.className='planet-row';const dot=document.createElement('i');dot.className='planet-dot';dot.dataset.planet=name;const text=document.createElement('span');text.textContent=name;b.append(dot,text);b.onclick=()=>{close();world?.visit(name);};content.lastChild.append(b);}};
$('#info').onclick=()=>open('<div class="definitions"><p><strong>Длить волю</strong> — устремлять явление в пространство-время.</p><p><strong>Акт воли</strong> — свет.</p><p><strong>Луч</strong> — направление воли. Каждый блик хранит один утверждённый этап. Выбери луч и веди курсор вдоль него; на телефоне проведи пальцем в его направлении.</p><details><summary>О пространстве</summary><p>Направления и формы орбит основаны на данных JPL на дату открытия. Расстояния сжаты, а размеры показаны в художественном масштабе: гиганты крупнее каменистых планет.</p><p>Показаны основные реальные спутники. Их размеры, орбиты и скорости анимации условны.</p><p>Качества планет — эзотерические образы для выбора направления воли. Вулкан — вымышленный визуальный образ из эзотерической традиции, а не подтверждённая планета.</p><a href="https://ssd.jpl.nasa.gov/planets/approx_pos.html" target="_blank" rel="noopener">JPL — орбиты</a><br><a href="https://www.theosophy.world/encyclopedia/sun" target="_blank" rel="noopener">Вулкан — эзотерическая традиция</a></details></div>','Определения');
$('#rays').onclick=showRays;
$('#history').onclick=()=>drawer.hidden?showHistory():closeHistory();$('#history-close').onclick=closeHistory;
$('.close').onclick=close;panel.addEventListener('cancel',e=>{e.preventDefault();close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){hideStage();closeHistory();context=null;expanded=false;updateActions();}});panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
sync();setInterval(sync,1000);addEventListener('storage',e=>{if(e.key===CONFIG.storageKey&&e.newValue){try{state=normalizeState(JSON.parse(e.newValue));current=state.acts.find(a=>a.endedAt===null&&state.rays.some(r=>r.id===a.rayId&&!r.deletedAt));render();if(!drawer.hidden)showHistory();}catch{}}});
function setupTelegram(){const tg=window.Telegram?.WebApp;if(!tg?.initData)return;tg.ready();tg.expand();tg.setHeaderColor('#06070b');tg.setBackgroundColor('#06070b');if(tg.isVersionAtLeast('7.7'))tg.disableVerticalSwipes();tg.BackButton.onClick(()=>panel.open?close():closeHistory());const update=()=>panel.open||!drawer.hidden?tg.BackButton.show():tg.BackButton.hide();new MutationObserver(update).observe(panel,{attributes:true,attributeFilter:['open']});new MutationObserver(update).observe(drawer,{attributes:true,attributeFilter:['hidden']});}if(document.readyState==='complete')setupTelegram();else addEventListener('load',setupTelegram,{once:true});
if(document.modelContext?.registerTool){const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t)).catch(()=>{})}catch{}};register({name:'read_will_acts',description:'Read saved acts, directed rays and planet goals.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({...state,acts:liveActs(),rays:liveRays(),storageAvailable:storageOK})});register({name:'start_will_act',description:'Save an act on an existing ray or a new named ray directed to a planet or infinity.',inputSchema:{type:'object',properties:{text:{type:'string',minLength:1,maxLength:500},target:{type:'string',enum:TARGETS},rayId:{type:'string'},name:{type:'string',maxLength:80},goal:{type:'string',maxLength:300},color:{type:'string',enum:RAY_COLORS.map(c=>c[0])}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:i=>approve(i.text,i.target||'Бесконечность',i.rayId||'new',i.name||'',{goal:i.goal,color:i.color})});}

if(window.visualViewport){const fitKeyboard=()=>document.documentElement.style.setProperty('--visible-height',Math.round(visualViewport.height)+'px');visualViewport.addEventListener('resize',fitKeyboard);fitKeyboard();}
