import * as THREE from 'three';
import {haloTexture} from './surfaces.js';

// Kept separate from the acts so future palettes/patterns can change without migrating history.
export const STAR_STYLE = Object.freeze({pattern:'plasma',violet:'#936cff',cyan:'#52d9ee',rose:'#fa5d98',scarlet:'#ed5779'});
export function fieldForActs(count){
 const value=Number(count),steps=Number.isFinite(value)?Math.max(0,Math.floor(value)):0;
 return {steps,radius:steps===0?.052:.12+.135*Math.pow(steps,.68),energy:1-Math.exp(-steps/12)};
}
export function createStarField(mobile){
 const group=new THREE.Group();let target=fieldForActs(0),radius=target.radius,energy=0;
 const uniforms={time:{value:0},energy:{value:0},outside:{value:1},violet:{value:new THREE.Color(STAR_STYLE.violet)},cyan:{value:new THREE.Color(STAR_STYLE.cyan)},rose:{value:new THREE.Color(STAR_STYLE.rose)},scarlet:{value:new THREE.Color(STAR_STYLE.scarlet)}};
 const vertex=`varying vec3 p;varying vec3 n;varying vec3 v;void main(){p=position;vec4 q=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);v=normalize(-q.xyz);gl_Position=projectionMatrix*q;}`;
 const fragment=`uniform float time;uniform float energy;uniform float outside;uniform vec3 violet;uniform vec3 cyan;uniform vec3 rose;uniform vec3 scarlet;varying vec3 p;varying vec3 n;varying vec3 v;
 float hash(vec3 q){q=fract(q*.3183099+vec3(.11,.37,.73));q*=17.;return fract(q.x*q.y*q.z*(q.x+q.y+q.z));}
 float noise(vec3 q){vec3 i=floor(q),f=fract(q);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
 void main(){vec3 q=normalize(p);float t=time*.085;vec3 flow=vec3(noise(q*3.+t),noise(q*3.7-t*.8+4.),noise(q*4.2+t*.65+8.));float cells=noise(q*10.+flow*2.8);float small=noise(q*28.+flow*4.+t);float filament=pow(1.-abs(cells*2.-1.),16.);float sparkle=pow(smoothstep(.64,.88,small),3.);float hue=noise(q*1.8+flow*.45+t*.12);vec3 c=mix(violet,cyan,smoothstep(.22,.54,hue));c=mix(c,rose,smoothstep(.53,.74,hue));float facing=abs(dot(normalize(n),normalize(v)));float rim=pow(1.-facing,2.5);c=mix(c,scarlet,rim*.43);float brightness=.30+cells*.45+filament*(.65+energy*.6)+sparkle*.55;c*=brightness;c+=vec3(.65,.78,.88)*pow(filament,3.)*.25;float alpha=(.62+energy*.25)*(.68+facing*.32)*outside;if(!gl_FrontFacing)alpha*=.12;gl_FragColor=vec4(c,alpha);}`;
 const skin=new THREE.Mesh(new THREE.SphereGeometry(1,mobile?48:64,mobile?32:48),new THREE.ShaderMaterial({uniforms,vertexShader:vertex,fragmentShader:fragment,transparent:true,side:THREE.DoubleSide,depthWrite:false}));group.add(skin);
 const corona=new THREE.Sprite(new THREE.SpriteMaterial({map:haloTexture(),transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,opacity:.3}));group.add(corona);
 const shell=new THREE.Mesh(skin.geometry,new THREE.ShaderMaterial({uniforms,vertexShader:vertex,fragmentShader:`uniform float time;uniform float energy;uniform float outside;varying vec3 p;varying vec3 n;varying vec3 v;void main(){float rim=pow(1.-abs(dot(normalize(n),normalize(v))),3.);float flicker=.8+.2*sin(p.x*17.+p.y*23.+p.z*11.+time*.6);vec3 color=mix(vec3(.35,.67,1.),vec3(.95,.29,.55),.5+.5*sin(p.x*3.+p.z*4.));gl_FragColor=vec4(color,rim*flicker*(.12+energy*.18)*outside);}`,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));shell.scale.setScalar(1.07);group.add(shell);
 const dots=[],colors=[];for(let i=0;i<(mobile?120:220);i++){const y=1-2*(i+.5)/(mobile?120:220),a=i*2.399963,r=Math.sqrt(1-y*y)*1.025;dots.push(Math.cos(a)*r,y*1.025,Math.sin(a)*r);const c=new THREE.Color([STAR_STYLE.violet,STAR_STYLE.cyan,STAR_STYLE.rose][i%3]);colors.push(c.r,c.g,c.b);}
 const sparkGeo=new THREE.BufferGeometry();sparkGeo.setAttribute('position',new THREE.Float32BufferAttribute(dots,3));sparkGeo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));
 const sparks=new THREE.Points(sparkGeo,new THREE.ShaderMaterial({uniforms,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,vertexColors:true,vertexShader:`uniform float time;uniform float energy;varying vec3 tint;varying float twinkle;void main(){tint=color;twinkle=.3+.7*pow(.5+.5*sin(time*1.1+position.x*37.+position.y*21.),5.);vec4 p=modelViewMatrix*vec4(position,1.);gl_PointSize=1.5+twinkle*2.;gl_Position=projectionMatrix*p;}`,fragmentShader:`uniform float energy;uniform float outside;varying vec3 tint;varying float twinkle;void main(){float d=length(gl_PointCoord-.5)*2.;gl_FragColor=vec4(mix(tint,vec3(1.),.4),pow(max(0.,1.-d),2.)*twinkle*(.3+energy)*outside);}`}));group.add(sparks);
 return {group,setActs(count){target=fieldForActs(count);return target;},get radius(){return radius;},get target(){return target;},update(dt,time,distance,atCenter=false){const ease=1-Math.exp(-dt*2.8);radius=THREE.MathUtils.lerp(radius,target.radius,ease);energy=THREE.MathUtils.lerp(energy,target.energy,ease);uniforms.time.value=time;uniforms.energy.value=energy;const outside=atCenter?0:THREE.MathUtils.smoothstep(distance, radius*.75,radius*1.7);uniforms.outside.value=THREE.MathUtils.lerp(.035,1,outside);group.scale.setScalar(radius);skin.rotation.set(time*.014,time*.023,time*.008);sparks.rotation.copy(skin.rotation);corona.scale.setScalar(6.2+energy*.6);corona.material.opacity=(.38+energy*.48)*(.08+.92*outside);}};
}
